### ISSUE TITLE
Fix: ulimit is low. 

### ISSUE THREAD

**Issue by rajangohil99** [SaiTeja69/Digital_Text_To_Handwriting#1]
Rajans-MacBook-Air:Digital_Text_To_Handwriting rajan$ python3 imagehand.py 
Traceback (most recent call last):
  File "imagehand.py", line 43, in <module>
    make_image(list1,count)
  File "imagehand.py", line 6, in make_image
    imgs    = [ Image.open(i) for i in list1 ]
  File "imagehand.py", line 6, in <listcomp>
    imgs    = [ Image.open(i) for i in list1 ]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/PIL/Image.py", line 2843, in open
    fp = builtins.open(filename, "rb")
OSError: [Errno 24] Too many open files: 'fonts/s.jpg'
Rajans-MacBook-Air:Digital_Text_To_Handwriting rajan$

**Comment by rajangohil99** [comment]
Can be fixed with 
ulimit -n 4096

**Comment by ForceGT** [comment]
PR dedo sir

**Comment by SaiTeja69** [comment]
Load all the images in a list before you start , using this list instead of
reopening filed again and again . 🤘 Will fix it then
